apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: server-service
  labels:
    release: server
spec:
  selector:
    matchLabels:
      app: server 
  endpoints:
  - port: http-port 
    path: /metrics