apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todo-server-monitor
  labels:
    release: monitoring 
spec:
  selector:
    matchLabels:
      app: server 
  endpoints:
  - port: 5000 
    path: /metrics