pipeline {
    agent any

    triggers {
        githubPush()
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
               
                dir('server') {
                    sh 'npm install'
                }
            }
        }

        stage('Build') {
            steps {
               
                dir('server') {
                    sh 'npm run build'
                }
            }
        }

        stage('Deploy') {
            steps {
             
                dir('server') {
                    sh 'pm2 delete todo-backend || true'
                    sh 'pm2 start dist/index.js --name todo-backend'
                    sh 'pm2 save'
                }
            }
        }
    }
}