node {
    withEnv(['PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin']) {
        
        stage('Checkout Code') {
            checkout scm
        }

        stage('Install Dependencies') {
            dir('server') {
                sh 'npm install'
            }
        }

        stage('Build') {
            dir('server') {
                sh 'npm run build'
            }
        }

      
        stage('Server Code Analysis') {
            withSonarQubeEnv('sonar-server') {
                def SCANNER_HOME = tool name: 'sonar-scanner', type: 'hudson.plugins.sonar.SonarRunnerInstallation'
                dir('server') {
                    sh """
                        ${SCANNER_HOME}/bin/sonar-scanner \
                        -Dsonar.host.url=http://172.17.0.1:9000 \
                        -Dsonar.projectKey=devops-project-backend \
                        -Dsonar.projectName="todo-list: DevOps Project " \
                        -Dsonar.projectVersion=0.1.0 \
                        -Dsonar.sources=. \
                        -Dsonar.exclusions="node_modules/**, dist/**" \
                        -Dsonar.javascript.node.maxSpace=4096
                    """
                }
            }
        }

        stage("Quality Gate Status") {
            timeout(time: 10, unit: 'MINUTES') { 
                waitForQualityGate abortPipeline: true
            }
        }

        stage('Deploy') {
            dir('server') {
                sh 'npx pm2 delete todo-backend || true'
                sh 'npx pm2 start dist/index.js --name todo-backend'
                sh 'npx pm2 save'
            }
        }
    }
}